name: Run Extract SS Script

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pyaes requests

      - name: Run Python script
        run: python extract_ss.py

      - name: Commit ss_links.txt
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ss_links.txt
          git commit -m "Update SS links $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes"

      - name: Push changes with PAT
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
